#######################################################################################
# Book settings
title: Основи програмування <br/> мовою С
author: Громова В.В.
logo: content/images/logo/logo.png

exclude_patterns: [_*, .*, tools, README.md, content/LICENSE.md, content/example.ipynb]

#description: >-
#  Методичні вказівки до виконання лабораторних робіт
#  із кредитного модуля "Програмування-2. С"

#######################################################################################
# Html settings
html:
  favicon: content/images/logo/favicon.ico
  extra_navbar: <a href="mailto:vikvikgrom@gmail.com">Громова В.В.</a>, 2020
  extra_footer: This page was created by <a href="https://github.com/gasperpaul/c-labs-book/graphs/contributors">сommunity</a>.
  home_page_in_navbar: true
  baseurl: https://gasperpaul.github.io/c-labs-book

#######################################################################################
# Interact link settings
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: https://mybinder.org
  thebe: false

repository:
  url: https://github.com/GasperPaul/c-labs-book
  branch: master
  path_to_book: ''

#######################################################################################
# Execution settings
execute:
  execute_notebooks: cache
